### PR TITLE
Add a canvas layer with a fade in/fade out screen animation to screen…

### PR DESCRIPTION
**Pull request by godouuu**
… manager scene. Add transition animation to GoToScreen function

# Description

Adds a fade out screen transition animation when switching between screens. Updated the GoToScreen function parameter to require a bool for the screen transition animation 

## Related issue(s)

Related to https://github.com/Saplings-Projects/Birthday-2024/issues/17
Not a 3D page turning animation yet but it's a start and is at least a somewhat less jarring transition between screens

## List of changes

Updated
- ScreenManager.gd - Updated the GoToScreen function with a bool parameter for doing the screen transition animation
- Updated scripts using the GoToScreen function to use the new bool param
- scene_mngr_init_scene.tscn - Added a canvas layer (TransitionLayer), animation player, and color rect for the fade out screen animation

### CODE REVIEW

**Review by Mikotey — CHANGES_REQUESTED** [review]
Looks good!
Only issue I encountered is the splash screen or the very first transition seems to be strange. At least for me, the game starts black, then the splash screen pops into view as it fades out to go to main menu

Once that's fixed, should be all set!

**Comment by godouuu** [comment]
@Mikotey Latest commit should fix that first splash screen fade transition

**Comment by Mikotey** [comment]
@godouuu 
Now it shows the empty init scene before transitioning to the splash screen.
If it could fade into the splash without the fade out, that would be ideal.
But an easy fix could be to add a full-screen black rect to the back of the init scene.
At least then the fade isn't apparent as it transitions.

**Comment by godouuu** [comment]
@Mikotey added that base layer to the init scene. That layer is still kind of visible in the main menu screen now though (main menu scene is noticeably darker than before). It probably won't be visible anymore once the UI for the main menu is completed and is put on a higher layer

**Comment by Casulono** [comment]
Hopefully the layer will behave as you say after UI addition

**Review by Casulono — APPROVED** [review]

**Review by Mikotey — APPROVED** [review]
Yeah, it should be fine since the updated main menu will use opaque art so it won't show the init scene behind it like it currently does.

**Pull request merged**
